### ISSUE TITLE
user enter pin code which is incorrect

### ISSUE THREAD

**Issue by welissonArley** [welissonArley/Packages.MAUI#10]
If user enter pin code which is incorrect, the pin entry must be cleared which is entered for new entry. The keyboard removal working but there should be some option to clear it programmatically.

**Comment by tmosx189** [comment]
Is this issue stil open?

**Comment by welissonArley** [comment]
Working on that. Doing some test to check if it's working properly and solving small bugs before release

**Comment by welissonArley** [comment]
Hi @tmosx189 there is a new version fixing this bug. Anything else letme know :)
